import type { ActiveRun, HourlyResult, LaunchDraft, WorldMetadata } from '../../domain/types'
import type { ActivePlan, CampaignFacts, CompletedRun, PendingPlanningRound } from '../../domain/planning'
import { zeroCampaignFacts } from '../../domain/campaignFacts'
import type { FieldErrors } from './validation'
import { initialDraft } from './validation'
export interface CampaignState {draft:LaunchDraft;activeDraft:LaunchDraft|null;session:ActiveRun|null;history:HourlyResult[];facts:CampaignFacts;activePlan:ActivePlan|null;completedRuns:CompletedRun[];pendingRound:PendingPlanningRound|null;planning:'idle'|'planning'|'replanning'|'replan_failed';busy:boolean;error:string|null;fieldErrors:FieldErrors}
export type CampaignAction=|{type:'draft';draft:LaunchDraft}|{type:'begin'}|{type:'invalid';errors:FieldErrors}|{type:'failed';error:string;fieldErrors?:FieldErrors}|{type:'created';session:ActiveRun;activeDraft:LaunchDraft;activePlan:ActivePlan;facts:CampaignFacts}|{type:'facts-committed';session:ActiveRun;history:HourlyResult[];facts:CampaignFacts;pendingRound:PendingPlanningRound}|{type:'replanned';activePlan:ActivePlan}|{type:'replan-failed';error:string;pendingRound:PendingPlanningRound}|{type:'retry-replan';pendingRound:PendingPlanningRound}|{type:'clear-error'}
export function createCampaignState(metadata:WorldMetadata):CampaignState{return{draft:initialDraft(metadata),activeDraft:null,session:null,history:[],facts:zeroCampaignFacts(metadata.channelIds),activePlan:null,completedRuns:[],pendingRound:null,planning:'idle',busy:false,error:null,fieldErrors:{}}}
export function campaignReducer(state:CampaignState,action:CampaignAction):CampaignState{switch(action.type){case'draft':return{...state,draft:action.draft,fieldErrors:{},error:null};case'begin':return{...state,busy:true,planning:'planning',error:null,fieldErrors:{}};case'invalid':return{...state,busy:false,fieldErrors:action.errors};case'failed':return{...state,busy:false,planning:'idle',error:action.error,fieldErrors:action.fieldErrors??state.fieldErrors};case'created':{const completed=state.session?.status==='finished'&&state.activeDraft&&state.activePlan?[...state.completedRuns.filter(run=>run.strategy!==state.activeDraft!.campaign.strategy),{strategy:state.activeDraft.campaign.strategy,optimize:state.activeDraft.campaign.optimize,planId:state.activePlan.planId,facts:state.facts}].slice(-2):state.completedRuns;return{...state,busy:false,planning:'idle',session:action.session,activeDraft:action.activeDraft,activePlan:action.activePlan,history:[],facts:action.facts,completedRuns:completed,pendingRound:null,error:null,fieldErrors:{}}}case'facts-committed':return{...state,session:action.session,history:action.history,facts:action.facts,pendingRound:action.pendingRound,planning:'replanning',error:null};case'replanned':return{...state,activePlan:action.activePlan,pendingRound:null,planning:'idle',error:null};case'replan-failed':return{...state,pendingRound:action.pendingRound,planning:'replan_failed',error:action.error};case'retry-replan':return{...state,pendingRound:action.pendingRound,planning:'replanning',error:null};case'clear-error':return{...state,error:null}}}
