import type { ActiveRun, HourlyResult, LaunchDraft, WorldMetadata } from '../../domain/types'
import type { ActivePlan, CampaignFacts, CompletedRun, InfeasibleTargetPlan, PendingPlanningRound } from '../../domain/planning'
import { zeroCampaignFacts } from '../../domain/campaignFacts'
import { buildPastCampaignPayload, loadPastCampaigns, type PastCampaignRecord } from '../../domain/history'
import type { FieldErrors } from './validation'
import { initialDraft } from './validation'
/** One accepted plan: revision 0 is the approved plan, later revisions come from hourly replanning. */
export interface PlanRevision {revision:number;hour:number;plan:ActivePlan}
export interface CampaignState {draft:LaunchDraft;planRevisions:PlanRevision[];diagnosis:InfeasibleTargetPlan|null;activeDraft:LaunchDraft|null;session:ActiveRun|null;history:HourlyResult[];facts:CampaignFacts;activePlan:ActivePlan|null;approvedPlan:ActivePlan|null;historyCount:number;pastCampaigns:PastCampaignRecord[];completedRuns:CompletedRun[];pendingRound:PendingPlanningRound|null;planning:'idle'|'planning'|'replanning'|'replan_failed';busy:boolean;error:string|null;fieldErrors:FieldErrors}
export type CampaignAction=|{type:'draft';draft:LaunchDraft}|{type:'begin'}|{type:'invalid';errors:FieldErrors}|{type:'failed';error:string;fieldErrors?:FieldErrors}|{type:'created';session:ActiveRun;activeDraft:LaunchDraft;activePlan:ActivePlan;facts:CampaignFacts;historyCount?:number}|{type:'facts-committed';session:ActiveRun;history:HourlyResult[];facts:CampaignFacts;pendingRound:PendingPlanningRound|null}|{type:'clear-history'}|{type:'replace';state:CampaignState}|{type:'replanned';activePlan:ActivePlan}|{type:'infeasible';diagnosis:InfeasibleTargetPlan}|{type:'replan-failed';error:string;pendingRound:PendingPlanningRound}|{type:'retry-replan';pendingRound:PendingPlanningRound}|{type:'clear-error'}
export function createCampaignState(metadata:WorldMetadata):CampaignState{return{draft:initialDraft(metadata),planRevisions:[],diagnosis:null,activeDraft:null,session:null,history:[],facts:zeroCampaignFacts(metadata.channelIds),activePlan:null,approvedPlan:null,historyCount:0,pastCampaigns:loadPastCampaigns().filter(record=>record.worldConfigDigest===metadata.worldConfigDigest),completedRuns:[],pendingRound:null,planning:'idle',busy:false,error:null,fieldErrors:{}}}
/** A finished run becomes observable history for later campaigns on the same market. */
export function archiveFinishedRun(state:CampaignState):PastCampaignRecord[]{const {session,activeDraft,activePlan}=state;if(!session||session.status!=='finished'||!activeDraft||!activePlan||state.history.length===0)return state.pastCampaigns;if(state.pastCampaigns.some(record=>record.planId===activePlan.planId&&record.campaignSeed===activeDraft.simulation.campaignSeed))return state.pastCampaigns;const record:PastCampaignRecord={audience:activeDraft.simulation.audience,worldConfigDigest:session.worldConfigDigest,worldSeed:activeDraft.simulation.worldSeed,campaignSeed:activeDraft.simulation.campaignSeed,simulationId:session.simulationId,planId:activePlan.planId,finishedAt:session.currentHour,durationHours:session.durationHours,budget:activePlan.budget,optimize:activePlan.optimize,facts:state.facts,payload:buildPastCampaignPayload(state.history,session.channelIds,session.timeZone,session.durationHours)};return[...state.pastCampaigns,record].slice(-12)}
export function campaignReducer(state:CampaignState,action:CampaignAction):CampaignState{switch(action.type){case'draft':return{...state,draft:action.draft,fieldErrors:{},error:null,diagnosis:null};case'begin':return{...state,busy:true,planning:'planning',error:null,fieldErrors:{},diagnosis:null};case'infeasible':return{...state,busy:false,planning:'idle',error:null,diagnosis:action.diagnosis};case'invalid':return{...state,busy:false,fieldErrors:action.errors};case'failed':return{...state,busy:false,planning:'idle',error:action.error,fieldErrors:action.fieldErrors??state.fieldErrors};case'created':{const finished=state.session?.status==='finished'&&state.activeDraft&&state.activePlan;const completed=finished?[...state.completedRuns.filter(run=>run.strategy!==state.activeDraft!.campaign.strategy||run.execution!==state.activeDraft!.campaign.execution),{strategy:state.activeDraft!.campaign.strategy,optimize:state.activeDraft!.campaign.optimize,planId:state.activePlan!.planId,facts:state.facts,execution:state.activeDraft!.campaign.execution,historyCount:state.historyCount,planSpend:state.approvedPlan?.expected?.spend??null,planKpi:state.approvedPlan?.expected?.[state.activePlan!.optimize==='unique_reach'?'uniqueReach':state.activePlan!.optimize]??null}].slice(-3):state.completedRuns;return{...state,busy:false,planning:'idle',session:action.session,activeDraft:action.activeDraft,activePlan:action.activePlan,approvedPlan:action.activePlan,planRevisions:[{revision:0,hour:0,plan:action.activePlan}],diagnosis:null,historyCount:action.historyCount??0,pastCampaigns:archiveFinishedRun(state),history:[],facts:action.facts,completedRuns:completed,pendingRound:null,error:null,fieldErrors:{}}}case'facts-committed':{const planning:CampaignState['planning']=action.pendingRound?'replanning':'idle';const next:CampaignState={...state,session:action.session,history:action.history,facts:action.facts,pendingRound:action.pendingRound,planning,error:null};return action.session.status==='finished'?{...next,pastCampaigns:archiveFinishedRun(next)}:next}case'clear-history':return{...state,pastCampaigns:[]};case'replanned':return{...state,activePlan:action.activePlan,planRevisions:[...state.planRevisions,{revision:state.planRevisions.length,hour:state.facts.currentHour,plan:action.activePlan}],pendingRound:null,planning:'idle',error:null};case'replan-failed':return{...state,pendingRound:action.pendingRound,planning:'replan_failed',error:action.error};case'retry-replan':return{...state,pendingRound:action.pendingRound,planning:'replanning',error:null};case'clear-error':return{...state,error:null};case'replace':return action.state}}
